### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by quincy** [fulldump/goconfig#3]
Great job!  The biggest thing missing is a released version.

http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by fulldump** [comment]
Hello quincy,
Thanks for your advice and for the article link. First release done: [https://github.com/fulldump/goconfig/releases/tag/v1.0.0](https://github.com/fulldump/goconfig/releases/tag/v1.0.0)

**Comment by quincy** [comment]
Thank you!
