### ISSUE TITLE
Syntactically incorrect Struct Tags

### ISSUE THREAD

**Issue by ghost** [fulldump/goconfig#4]
GoConfig's Struct Tags don't conform to go convention. https://golang.org/pkg/reflect/#StructTag . This doesn't really interfere with using other struct tags, but it is a syntactically incorrect usage of Struct Tags. 
Instead of just using a value like:

```
type config {
    Number int `A number to use`
}
```

something like this could be used instead:

```
type config {
    Number int `goconfig: "A number to use"`
}
```

**Comment by fulldump** [comment]
Hi @woodlander87,
The reason of that decision is making it as simple as possible. Tag `json` is no needed because GoConfig has its own mapping to export to JSON.

Do you think there are common use cases that would need tags?

Maybe it is possible implement a kind of logic to maintain both alternatives.

I really appreciate comments, thanks!

**Comment by ghost** [comment]
I appreciate the simplicity, but if a struct needs to implement other tags, it adds quite a bit of unnecessary text to the -help flag.
For example:

```
type config struct {
    Number int `A number to use json:"number"`
}
```

results in:

```
  -number int
        A number to use json:"number"
```

on the command line.

**Comment by quincy** [comment]
This also causes `go vet` to spit out some warnings.

```
main.go:31: struct field tag `A number to use` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```

I really love the simplicity as it is now, but I think @woodlander87 is probably right.

**Comment by fulldump** [comment]
Definitely @woodlander87 is right. There are two big points:
- `go vet` throwing warnings
- GoConfig is making a decision by the user (bad sign)

I will do the change in few days.

Thanks for your feedback, I really appreciate it.

**Comment by copitux** [comment]
Lol, didn't see this issue (#5). On your own dude ;)

**Comment by fulldump** [comment]
Feature finished! thanks to @copitux and @woodlander87
